### ISSUE TITLE
[Objectron]  unity quits suddenly or doesn't output anything

### ISSUE THREAD

**Issue by FrankSpalteholz** [asus4/tf-lite-unity-sample#103] opened 2021-03-02 08:36 UTC
Hi, i'm currently trying to implement objectron for sneakers detection but without any luck so far. I was trying both models: 
[1] object_detection_3d_sneakers.tflite and [2]  object_detection_3d_sneakers_1stage.tflite By using the first one unity imidiatly crashes which might be due to an user-error of mine but the second one at least is loading/initializing successfully. I was stripping down the FaceMesh-class and changed the input and output according to the model-definition. But when i run this model the first tensor should actually output confidence-values between 0 and 1 for a 40x30 array. But it's empty ... have you ever tried using this model so far? The whole invoke->model->process->getting data back procedure is capsulated in the plugin so it's hard to debug or tell where my mistakes are comming from. 
Thank you so much for this plug-in (again!)
Frank

**Comment by FrankSpalteholz** [comment] 2021-03-02 20:11
After some more investigations i've found out that by disabling GPU i'm getting promissing output-values in both output-tensors by using "object_detection_3d_sneakers_1stage.tflite" ... but now it's very slow ofcourse. Do you have any suggestions about why this is not working in gpuDelegate-mode? I'm still prototyping in the editor on OSX but later i will have to switch to iOS.

**Comment by asus4** [comment] 2021-03-03 04:46
Hi @FrankSpalteholz, 

I've tested the two-stage model `object_detection_3d_sneakers.tflite` on macOS and iOS, with the Metal delegate. and it seemed to work without any errors. I'm not sure why it crashes in your mac 🤔

**Comment by FrankSpalteholz** [comment] 2021-03-03 08:20
Hi Koki! **Thank you** for getting back to me so quickly. And it's good to know that it's been working on your side. Could you please post your initialization for the dectector-class that's derived from BaseImagePredictor. I fear that this is the part where i maybe messed up something. I was creating input and outputs according to the definitions (you can't actually make mistakes on that since you are outputing these tensor-sizes anyways) but i'm still struggeling by initializing the options ... so again ... i'd really appreciate if you could post your test-init for at least the 1stage-model so that i could maybe go from there and try adopting this towards the 2stage model. Thank you!!!

**Comment by asus4** [comment] 2021-03-04 07:36
Sorry, @FrankSpalteholz, I wrote Objectron’s code for work, so it’s difficult to share it. Please make sure again that your input/output size, format are correct.

**Comment by FrankSpalteholz** [comment] 2021-03-04 21:48
Hi Koki ... no need to post full working code. It's just that i'm still confused about the fact that i'm initializing my detector-class without gpu ... it works. It's slow like hell (like expected) but i do indeed get out usefull values. But the same code WITH gpu (just setting the true-flag) makes Unity crash hardly. So there is definitely a mistake on my side but i don't get a meaningful starting point. So this is my part where i'm initializing my detector-class:

        private float[,] outputs0;
        private float[,] outputs1;
        private Result result;
       
        public ObjectronDetect(string modelPath) : base(modelPath,true)
        {
           //based on your pose-net example
            var odim0 = interpreter.GetOutputTensorInfo(0).shape;
            var odim1 = interpreter.GetOutputTensorInfo(1).shape;
            outputs0 = new float[odim0[0], odim0[1]]; // [1,18]
            outputs1 = new float[odim1[0], odim1[1]]; // [1,1]

        }

        public override void Invoke(Texture inputTex)
        {

            ToTensor(inputTex, input0);
            interpreter.SetInputTensorData(0, input0);
            interpreter.Invoke();
            interpreter.GetOutputTensorData(0, outputs0);
            interpreter.GetOutputTensorData(1, outputs1);
        }

The strange thing is that even without calling the invoke function and just create an instance of this ObjectronDetect-class it crashes. I guess there is something missing about the base-class. I'd really appreciate your guidance.
Thanks a lot!
F

**Comment by asus4** [comment] 2021-03-05 09:19
@FrankSpalteholz , I think I've probably found the cause. Your code seems OK. But the metal delegate for TensorFlow v2.4.0 has an error with the MediaPipe model. Can you try it with v2.3.1 3cb6e84386a0860d46670c837c0a3b06f3bd0dc3 ?

**Comment by FrankSpalteholz** [comment] 2021-03-05 11:37
Haha ... I had the same idea, switching back to the version from last year, where i was fumbling around with the iris-tracking. Anyway ... i can confirm that with TF-version 2.3.0 all stage2 models are running in gpu-delegate-mode. (but stage1-models are still outputing nothing - correct me if i'm wrong but those stage2 models are quantized versions and stage1 not ... could this be the reason why they are not working on gpu?) But for my prototype stage2 gives me "enough to play with" and its faster anyways compared to stage1. I'm good to go now but thank you very much for investigating this too. I'd appreciate if could drop a line here when you've found the time to fix the issue for version 2.4.0!

**Comment by asus4** [comment] 2021-03-05 12:31
The same crash occurs in r2.4.0 and r2.4.1, but it seems to be fixed in the master branch of TensorFlow.

I think this issue has something to do with it.
https://github.com/tensorflow/tensorflow/issues/43615

**Closed** 2021-03-05 15:06 UTC

**Comment by asus4** [comment] 2021-03-05 15:10
Updated the TensorFlow library to the master branch version. Hope this fixes the issue.

**Comment by FrankSpalteholz** [comment] 2021-03-05 15:18
Thank you mister!
